# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [master]
  pull_request:
    branches: [master]

env:
  stackName: Bootstrap
  secreto: ${{secrets.COGNITO_PASSWORD}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: github.event.pull_request.draft == false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: Write-Host "build...ing"
        shell: pwsh

      - name: UTs
        run: "[Environment]::SetEnvironmentVariable('pila', '${{ env.stackName }}')"
        shell: pwsh

      - name: Leer el maera
        run: |
          Write-Host "El kany es ${{ env.secreto }}"
          Start-Sleep -s 10
        shell: pwsh

      - name: Chequeando Antes
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando A
          status: in_progress

      - name: Leer el stack A
        id: leer-stack-a
        run: ./a.ps1
        shell: pwsh

      - name: Chequeando Despues
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando A
          conclusion: ${{ steps.leer-stack-a.outcome }}

      - name: Chequeando Antes
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando B
          status: in_progress

      - name: Leer el stack B
        id: leer-stack-b
        run: Write-Host ${{ steps.leer-stack-a.outputs }}
        shell: pwsh

      - name: Chequeando Despues
        if: failure()
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando B
          conclusion: ${{ steps.leer-stack-b.outcome }}

      - name: Chequeando Antes
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando C
          status: in_progress

      - name: Leer el stack C
        if: always()
        id: leer-stack-c
        run: Write-Host "paso C"
        shell: pwsh

      - name: Chequeando Despues
        if: always()
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Probando C
          conclusion: ${{ steps.leer-stack-c.outcome }}

      - name: Siempre corre
        if: always()
        run: Write-Host 'Haciendo limpieza'
        shell: pwsh
