# This is a basic workflow to help you get started with Actions

name: Stacks Cleanup

on:
  repository_dispatch:
    types: [stacks-cleanup]

env:
  stackName: Bootstrap
  secreto: ${{secrets.COGNITO_PASSWORD}}

jobs:
  Job-Limpieza:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Stacks Cleanup
        id: unico
        run: |
          Write-Host 'The stack is: ${{ github.event.client_payload.stack-name }}'
        shell: pwsh

      - name: Stacks Cleanup - GH Check
        if: always()
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Stacks Cleanup.
          conclusion: ${{ steps.unico.outcome }}
