name: A workflow for my Hello World file
on: workflow_dispatch
jobs:
    build:
      name: Hello world action
      runs-on: ubuntu-latest
      steps:
        - name: Principal
        uses: actions/checkout@v2
        run: Write-Host "hola"
        shell: pwsh

